# -*- coding: utf-8 -*-
"""pandas/matplotlib/ probability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzPrhrbMd5ySocqaZZYbNj0HauY-BVOO
"""

import pandas as pd
data = {
    "Employee_ID":["01","02","03","04","05","06","07","08","09","10"],
    "Salary":[34000,56000,67000,90500,78000,67000,89500,87000,54600,76400]
}
df=pd.DataFrame(data)
print(df)



df.shape

df.Salary

df.info()

df["Salary"].sort_values()

mean_Salary=df["Salary"].mean()
print(mean_Salary)

median_Salary=df["Salary"].median()
print(median_Salary)

mode_Salary=df["Salary"].mode()
print(mode_Salary)

mode_Salary=df["Salary"].mode()
print(mode_Salary)

# Range = Maximum - Minimum
Salary_range=df["Salary"].max()-df["Salary"].min()
print("Salary_range:",Salary_range)

# Variance ask: how much do the values vary around mean ?
# Company A = 30k,31k,32k,33k,34k
# company B = 10k , 20k, 32k, 44k
# variance = (data point - mean)^2/
Salary_variance=df["Salary"].var()
print("Salary_variance:",Salary_variance)

# Standard Deviation
Salary_std=df["Salary"].std()
print("Salary_std:",Salary_std)

#Percentiles
# Instead of asking only for the average what is I want is I want to know where a

print("50th percentile",
      df["Salary"].quantile(0.50))

q1 = df["Salary"].quantile(0.25)
q2 = df["Salary"].quantile(0.50)
q3 = df["Salary"].quantile(0.75)

print("Q1",q1)
print("Q2",q2)
print("Q3",q3)

iqr = q3 - q1
print("IQR",iqr)

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print("Lower Bound",lower_bound)
print("Upper Bound",upper_bound)

# Find the outliners
outliners = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]
print(outliners)

q1 = df["Salary"].quantile(0.25)
q2 = df["Salary"].quantile(0.50)
q3 = df["Salary"].quantile(0.75)

print("Q1",q1)
print("Q2",q2)
print("Q3",q3)

outliners = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]
print(outliners)

df.describe()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))
sns.histplot(df["Salary"])
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(9,5))
sns.histplot(df["Salary"], bins =8 , kde = True )
#plt.show()

import matplotlib.pyplot as plt

x = [0, 1, 2, 3, 4]
y = [0, 1, 4, 9, 16]

plt.plot(x, y)
#plt.show()

x=[0,1,2,3,4,5,6]
y=[12,34,21,67,32,45,32]
plt.plot(x,y)
plt.title("random number")
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
plt.show()

import matplotlib.pyplot as plt

x = [0, 2, 4, 6, 8]
y = [0, 4, 16, 36, 64]
fig, ax = plt.subplots()
ax.plot(x, y, marker='o', label="Data Points")

ax.set_title("Basic Components of Matplotlib Figure")
ax.set_xlabel("X-Axis")
ax.set_ylabel("Y-Axis")

ax.legend()
plt.show()

import matplotlib.pyplot as plt

x = ['Thur', 'Fri', 'Sat', 'Sun']
y = [170, 120, 250, 190]

plt.bar(x, y)
plt.title("Bar Chart")
plt.xlabel("Day")
plt.ylabel("Total Bill")
plt.show()

import matplotlib.pyplot as plt

x = ['Thur', 'Fri', 'Sat', 'Sun']
y = [170, 120, 250, 190]

plt.scatter(x, y)
plt.title("histogram Chart")
plt.xlabel("Day")
plt.ylabel("Total Bill")
plt.show()

import os
print(os.listdir(path))

import pandas as pd
df = pd.read_csv(os.path.join(path, "IPL.csv"))
df.head()

df.info()

df.isnull().sum()

df.drop_duplicates()

df.describe()

import random

dice = random.randint(1, 6)

print("Dice roll:", dice)

if dice == 4:
    print("4 aaya!")
else:
    print("4 nahi aaya.")

probability = 1 / 6

print("Probability of getting 4:", probability)
print("Probability in percentage:", probability * 100, "%")

# 20 coin
import numpy as np
result = np.random.choice(["Head","Tail"], size=20)
print(result)

#count Heads and tails
import numpy as np
result = np.random.choice(["Head","Tail"], size=10)
print(result)
heads = np.sum(result == "Head")
tails = np.sum(result == "Tail")
print(heads)
print(tails)

experiment_probabily = tails / 1000
print(experiment_probabily)

experiment_probabily = heads / 1000
print(experiment_probabily)

import random

total_rolls = int(input("Enter the total number of rolls: "))
count_4 = 0

for i in range(total_rolls):
    dice = random.randint(1, 6)

    if dice == 4:
        count_4 += 1

experimental_probability = count_4 / total_rolls

print("Total rolls:", total_rolls)
print("4 came:", count_4, "times")
print("Experimental probability:", experimental_probability)
print("Percentage:", experimental_probability * 100, "%")

import pandas as pd
data = {
    "Customer" : range(1,16) ,
    "Visited_before" :["yes","no","yes","no","yes","no","no","no","yes","no","yes","no","yes","yes","yes"] ,
    "Added_to_card" : ["yes","no","no","yes","no","no","yes","no","yes","no","yes","no","yes","no","yes"] ,
    "Purchased" : ["yes","no","yes","no","yes","no","yes","no","no","no","yes","no","yes","no","yes"]

}
df = pd.DataFrame(data)
print(df)

purchased_probability = (
    df["Purchased"] == "yes"
).mean()

print(purchased_probability)

# what is the probability of purchase given that he cutomer added something to cart?
purchased_given_added_to_card = (
    df[df["Added_to_card"] == "yes"]["Purchased"] == "yes"
).mean()

#print(purchased_given_added_to_card)
print(purchased_given_added_to_card * 100, "%")

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

scores = np.random.randint(0, 101, 1000)

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

scores = np.random.randint(0, 101, 1000)


from scipy.stats import norm
import numpy as np
import matplotlib.pyplot as plt
mean = 78
std = 10
x= np.linspace(30,110,500)
y=norm.pdf(x, mean, std)
plt.plot(x,y)

plt.xlabel("Exam Scores")
plt.ylabel("Probability Density")
plt.title("Normal Distribution of Exam Scores")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom

n=10
p = 0.30
x= np.arange(0,n+1)
probabilites = binom.pmf(x,n,p)
plt.bar(x,probabilites)
plt.xlabel("Number of Successes")
plt.ylabel("Probability")
plt.title("Binomial Distribution : 10 customers, purchase probability =")
plt.show()