# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3inZE7sCpBIppUQ_ULbGkZkpNBNtPzm
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("sudalairajkumar/covid19-in-india")

print("Path to dataset files:", path)

import os

print(os.listdir(path))

import pandas as pd

df = pd.read_csv(path + "/covid_19_india.csv")
df.head(10)

df["State/UnionTerritory"]

df.isnull().sum()

df.duplicated()

df.drop_duplicates()

df.info()

df.head()

df[df["State/UnionTerritory"] == "Kerala"]

df.isnull().sum()

df.isnull().sum()

#short krte hai ab
df.sort_values("Confirmed")

kerala = df[df["State/UnionTerritory"] == "Kerala"]
kerala["Confirmed"].sum()

#top case confirmed
df.sort_values("Confirmed", ascending=False).head(1)

#sabse jyda case kb huye
df.sort_values("Confirmed", ascending=False)

df.groupby("State/UnionTerritory")["Confirmed"].max()

df.groupby("State/UnionTerritory")["Confirmed"].sum()      #konse state me kitne case huye hai

df["Deaths"].sum()

df.loc[230:234, ["State/UnionTerritory", "Deaths", "Cured"]]

df.loc[45, ["State/UnionTerritory", "Deaths", "Cured"]]

df.head()

df["Date"] = pd.to_datetime(df["Date"])

df.loc[0, "Deaths"]

df.loc[5, "ConfirmedForeignNational"]

df.loc[5, "ConfirmedForeignNational"]

df.sample(10)    #rendom de raha ye

state_data = df.groupby("")

df.shape

df.info()

df.head()