# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BiudGXKWUwomWob62BmGNPf2lETEa4VD
"""

import pandas as pd
url = "https://huggingface.co/api/resolve-cache/datasets/prithivMLmods/Airbnb-Data-Map-Nyc/16fde005966ed7126da479d462d2fc0c87cba99c/AB_NYC_2019.csv?%2Fdatasets%2FprithivMLmods%2FAirbnb-Data-Map-Nyc%2Fresolve%2Fmain%2FAB_NYC_2019.csv=&etag=%22f01fb02e5a2ed4bba4ea85493266679e316ec861%22"
df = pd.read_csv(url)
print("Dataset loaded successfully!")

df.head(10)

df.isnull()

import kagglehub

# Download latest version
path = kagglehub.dataset_download("sudalairajkumar/covid19-in-india")

print("Path to dataset files:", path)

import os
print(os.listdir(path))

import pandas as pd
file_path = os.path.join(path, "covid_19_clean_complete.csv")
df=pd.read_csv(file_path)

df.head(3)

df.duplicated().sum()

df.drop_duplicates()

df.drop_duplicates()

df.info()

df["Date"] = pd.to_datetime(df["Date"])

df.info()

df.isnull().sum()

df.isnull().sum()

df.duplicated()

df.head(1)

state_data.head()

state_data.head()

state_data["Recovery_Rate"] = state_data["Recovery_Rate"].round(2)
state_data["Death_Rate"] = state_data["Death_Rate"].round(2)

from matplotlib import figure
#Tatal cases by State
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,5))
sns.barplot(
    data=state_data.sort_values("Confirmed",ascending=False),
    y="Province/State",
    x="Confirmed"
)
plt.title("Total Cases by State")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()